# Cloudflare Workers 配置文件
name = "personal-blog-api"
main = "worker.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# KV 命名空间配置
[[kv_namespaces]]
binding = "BLOG_KV"
preview_id = "your-preview-kv-namespace-id"
id = "your-production-kv-namespace-id"

# 环境变量（如果需要）
[vars]
ENVIRONMENT = "production"

# 路由配置（部署后配置）
# routes = [
#   { pattern = "yourdomain.com/api/*", zone_name = "yourdomain.com" }
# ]

# 开发环境配置
[env.development]
name = "personal-blog-api-dev"

[[env.development.kv_namespaces]]
binding = "BLOG_KV"
preview_id = "your-dev-kv-namespace-id"
id = "your-dev-kv-namespace-id"

[env.development.vars]
ENVIRONMENT = "development"