# Cloudflare Pages 配置文件
name = "person-blog-pages"
compatibility_date = "2024-01-15"

# Pages 配置
[build]
command = "echo 'No build step required for static site'"
publish = "public"

# 环境变量
[vars]
ENVIRONMENT = "production"

# 开发环境配置
[env.development]
name = "person-blog-pages-dev"

[env.development.vars]
ENVIRONMENT = "development"