# Cloudflare Pages 配置文件
name = "person-blog"
compatibility_date = "2024-01-15"

# Pages 项目配置
[env.production]
name = "person-blog"

# 构建配置
[build]
command = "echo 'No build step required'"
output_dir = "."

# 环境变量
[vars]
WORKER_URL = "https://awlayswm.com"
ENVIRONMENT = "production"