# Cloudflare Workers 配置文件
name = "personal-blog-api"
main = "worker.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# KV 命名空间配置
[[kv_namespaces]]
binding = "BLOG_KV"
preview_id = "32793f9a2ae74667a543c9881675c75c"
id = "32793f9a2ae74667a543c9881675c75c"

# 环境变量（如果需要）
[vars]
ENVIRONMENT = "production"

# 路由配置（部署后配置）
routes = [
  { pattern = "awlayswm.com/api/*", zone_name = "awlayswm.com" }
]

# 开发环境配置
[env.development]
name = "personal-blog-api-dev"

[[env.development.kv_namespaces]]
binding = "BLOG_KV"
preview_id = "32793f9a2ae74667a543c9881675c75c"
id = "32793f9a2ae74667a543c9881675c75c"

[env.development.vars]
ENVIRONMENT = "development"